In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('Wine.csv')

In [6]:
dataset.shape

(178, 14)

In [7]:
X = dataset.iloc[: , 0:13].values 

In [9]:
y = dataset.iloc[: , 13].values

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [14]:
X_train = sc.fit_transform(X_train)

In [15]:
sc.mean_

array([1.29848592e+01, 2.37260563e+00, 2.36690141e+00, 1.95549296e+01,
       1.00063380e+02, 2.25866197e+00, 1.94915493e+00, 3.63521127e-01,
       1.60605634e+00, 5.04521126e+00, 9.53352113e-01, 2.58626761e+00,
       7.42330986e+02])

In [16]:
sc.scale_

array([8.04327850e-01, 1.11142573e+00, 2.68732505e-01, 3.43040624e+00,
       1.41988964e+01, 6.09533681e-01, 9.72478678e-01, 1.27258178e-01,
       5.89135148e-01, 2.37201604e+00, 2.29106353e-01, 7.20093508e-01,
       3.02713380e+02])

In [17]:
X_test = sc.transform(X_test)

In [18]:
from sklearn.decomposition import PCA

In [32]:
pca= PCA(n_components = None)

In [20]:
X_train = pca.fit_transform(X_train)

In [22]:
X_test = pca.fit_transform(X_test)

In [29]:
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.35952175, 0.19820577, 0.14223855, 0.11215211, 0.06056091,
       0.03559827, 0.02705868, 0.01838811, 0.01375635, 0.01007092,
       0.00979244, 0.00798524, 0.0046709 ])

In [24]:
from sklearn.linear_model import LogisticRegression

In [26]:
classifier = LogisticRegression(random_state = 0)

In [33]:
classifier.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)